---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
    controller_validate_certs: "{{lookup('env', 'CONTROLLER_VERIFY_SSL')}}"
    controller_hostname: "{{lookup('env', 'CONTROLLER_HOST')}}"
    flatten_output: true
    local_path: "/tmp/{{repo_base}}"
    grupo: "lab-user"
    repo_base: "casc-awx"
    output_path: "{{local_path}}/filetree"
    repo_base_branch: master

  pre_tasks:
    - name: 3.4 Clonar el repositorio base localmente
      ansible.builtin.git:
        # La URL de clonaciÃ³n debe usar el nuevo PAT
        repo: "https://{{ git_token }}@{{ git_host }}/{{ grupo }}/{{ repo_base }}.git"
        dest: "{{ local_path }}"
        version: "{{ repo_base_branch }}"
        clone: yes
        update: yes

    - name: "Setup authentication (block)"
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ aap_hostname }}/api/v2/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always

    - name: Eliminar el directorio .git del clon para un nuevo historial
      ansible.builtin.file:
        path: "{{ output_path }}"
        state: absent
  roles:
    - infra.controller_configuration.filetree_create

  post_tasks:

    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ aap_hostname }}{{ aap_oauthtoken_url }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined

    - name: Commit push filetree
      ansible.builtin.command: "git status -s"
      args:
        chdir: "{{output_path}}"
      register: status_git

    - debug:
        msg: "{{status_git}}"

    - name: Commit push filetree
      ansible.builtin.command: "{{item}}"
      args:
        chdir: "{{output_path}}"
      loop:
        - git add .
        - git config --global user.email "{{git_user}}@example.com"
        - git config --global user.name "{{git_user}}"
        - git config http.sslVerify false
        - git commit -m 'Add new version filetree'
        - git push
      when: status_git.stdout  | length > 0
