---
controller_execution_environments:
  - name: "EE_AWX_Livecycle"
    description: ""
    image: "quay.io/adelahoz/ee_awx_livecycle:latest"
    pull: ""
  - name: "EE_AWX_Filetree_dispatch"
    description: ""
    image: "quay.io/adelahoz/ee_awx_filetree_dispatch:latest"
    pull: ""
...
