---
controller_settings:
  - settings:
      ACTIVITY_STREAM_ENABLED: "true"
      ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: "false"
      ORG_ADMINS_CAN_SEE_ALL_USERS: "true"
      MANAGE_ORGANIZATION_AUTH: "true"
      TOWER_URL_BASE: https://example-ansible-automation-platform.apps-crc.testing
      REMOTE_HOST_HEADERS:
        - REMOTE_ADDR
        - REMOTE_HOST
      PROXY_IP_ALLOWED_LIST: []
      CSRF_TRUSTED_ORIGINS: []
      LICENSE:
        sku: SER0569
        trial: true
        usage: ""
        pool_id: 2c945b7999bb1e750199de091feb6974
        satellite: false
        valid_key: true
        license_date: "1765515599"
        license_type: trial
        product_name: 60 Day Product Trial of Red Hat Ansible Automation Platform, Self-Supported (100 Managed Nodes)
        support_level: Self-Support
        account_number: "5910538"
        instance_count: 1
        subscription_id: "19875941"
        subscription_name: 60 Day Product Trial of Red Hat Ansible Automation Platform, Self-Supported (1 Managed Nodes)
      REDHAT_USERNAME: ""
      REDHAT_PASSWORD: ""
      SUBSCRIPTIONS_USERNAME: ""
      SUBSCRIPTIONS_PASSWORD: ""
      SUBSCRIPTIONS_CLIENT_ID: ""
      SUBSCRIPTIONS_CLIENT_SECRET: ""
      AUTOMATION_ANALYTICS_URL: https://cloud.redhat.com/api/ingress/v1/upload
      INSTALL_UUID: fc49096c-877b-4a09-8ad1-c7502c031040
      DEFAULT_CONTROL_PLANE_QUEUE_NAME: controlplane
      DEFAULT_EXECUTION_QUEUE_NAME: default
      # DEFAULT_EXECUTION_ENVIRONMENT: "null"
      CUSTOM_VENV_PATHS: []
      AD_HOC_COMMANDS:
        - command
        - shell
        - yum
        - apt
        - apt_key
        - apt_repository
        - apt_rpm
        - service
        - group
        - user
        - mount
        - ping
        - selinux
        - setup
        - win_ping
        - win_service
        - win_updates
        - win_group
        - win_user
      ALLOW_JINJA_IN_EXTRA_VARS: template
      AWX_ISOLATION_BASE_PATH: /tmp
      AWX_ISOLATION_SHOW_PATHS:
        - /etc/pki/ca-trust:/etc/pki/ca-trust:O
        - /usr/share/pki:/usr/share/pki:O
      AWX_TASK_ENV:
        HOME: /var/lib/awx
        GIT_SSL_NO_VERIFY: 'true'
      AWX_RUNNER_KEEPALIVE_SECONDS: "0"
      GALAXY_TASK_ENV:
        ANSIBLE_FORCE_COLOR: "false"
        GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
      INSIGHTS_TRACKING_STATE: "false"
      PROJECT_UPDATE_VVV: "false"
      AWX_ROLES_ENABLED: "true"
      AWX_COLLECTIONS_ENABLED: "true"
      AWX_SHOW_PLAYBOOK_LINKS: "false"
      AWX_MOUNT_ISOLATED_PATHS_ON_K8S: "false"
      GALAXY_IGNORE_CERTS: "false"
      STDOUT_MAX_BYTES_DISPLAY: "1048576"
      EVENT_STDOUT_MAX_BYTES_DISPLAY: "1024"
      MAX_WEBSOCKET_EVENT_RATE: "30"
      SCHEDULE_MAX_JOBS: "10"
      AWX_ANSIBLE_CALLBACK_PLUGINS: []
      DEFAULT_JOB_TIMEOUT: "0"
      DEFAULT_JOB_IDLE_TIMEOUT: "0"
      DEFAULT_INVENTORY_UPDATE_TIMEOUT: "0"
      DEFAULT_PROJECT_UPDATE_TIMEOUT: "0"
      ANSIBLE_FACT_CACHE_TIMEOUT: "0"
      MAX_FORKS: "200"
      # LOG_AGGREGATOR_HOST: "null"
      # LOG_AGGREGATOR_PORT: "null"
      # LOG_AGGREGATOR_TYPE: "null"
      LOG_AGGREGATOR_USERNAME: ""
      LOG_AGGREGATOR_PASSWORD: ""
      LOG_AGGREGATOR_LOGGERS:
        - awx
        - activity_stream
        - job_events
        - system_tracking
        - broadcast_websocket
        - job_lifecycle
      LOG_AGGREGATOR_INDIVIDUAL_FACTS: "false"
      LOG_AGGREGATOR_ENABLED: "false"
      LOG_AGGREGATOR_TOWER_UUID: ""
      LOG_AGGREGATOR_PROTOCOL: https
      LOG_AGGREGATOR_TCP_TIMEOUT: "5"
      LOG_AGGREGATOR_VERIFY_CERT: "true"
      LOG_AGGREGATOR_LEVEL: INFO
      LOG_AGGREGATOR_ACTION_QUEUE_SIZE: "131072"
      LOG_AGGREGATOR_ACTION_MAX_DISK_USAGE_GB: "1"
      LOG_AGGREGATOR_MAX_DISK_USAGE_PATH: /var/lib/awx
      LOG_AGGREGATOR_RSYSLOGD_DEBUG: "false"
      API_400_ERROR_LOG_FORMAT: status {status_code} received by user {user_name} attempting to access {url_path} from {remote_addr}
      # AUTOMATION_ANALYTICS_LAST_GATHER: "null"
      AUTOMATION_ANALYTICS_LAST_ENTRIES: ""
      AUTOMATION_ANALYTICS_GATHER_INTERVAL: "14400"
      IS_K8S: "true"
      BULK_JOB_MAX_LAUNCH: "100"
      BULK_HOST_MAX_CREATE: "100"
      BULK_HOST_MAX_DELETE: "250"
      UI_NEXT: "true"
      SUBSCRIPTION_USAGE_MODEL: unique_managed_hosts
      # CLEANUP_HOST_METRICS_LAST_TS: "null"
      # HOST_METRIC_SUMMARY_TASK_LAST_TS: "null"
      AWX_CLEANUP_PATHS: "true"
      AWX_REQUEST_PROFILE: "false"
      DEFAULT_CONTAINER_RUN_OPTIONS:
        - --network
        - slirp4netns:enable_ipv6=true
      RECEPTOR_RELEASE_WORK: "true"
      RECEPTOR_KEEP_WORK_ON_ERROR: "false"
      OPA_HOST: ""
      OPA_PORT: "8181"
      OPA_SSL: "false"
      # OPA_AUTH_TYPE: "null"
      OPA_AUTH_TOKEN: ""
      OPA_AUTH_CLIENT_CERT: ""
      OPA_AUTH_CLIENT_KEY: ""
      OPA_AUTH_CA_CERT: ""
      OPA_AUTH_CUSTOM_HEADERS: {}
      OPA_REQUEST_TIMEOUT: "1.5"
      OPA_REQUEST_RETRIES: "2"
      SESSION_COOKIE_AGE: "1800"
      SESSIONS_PER_USER: "-1"
      DISABLE_LOCAL_AUTH: "false"
      AUTH_BASIC_ENABLED: "true"
      OAUTH2_PROVIDER:
        ACCESS_TOKEN_EXPIRE_SECONDS: 31536000000
        AUTHORIZATION_CODE_EXPIRE_SECONDS: 600
        REFRESH_TOKEN_EXPIRE_SECONDS: 2628000
      ALLOW_OAUTH2_FOR_EXTERNAL_USERS: "false"
      LOGIN_REDIRECT_OVERRIDE: ""
      ALLOW_METRICS_FOR_ANONYMOUS_USERS: "false"
      PENDO_TRACKING_STATE: "off"
      CUSTOM_LOGIN_INFO: ""
      CUSTOM_LOGO: ""
      MAX_UI_JOB_EVENTS: "4000"
      UI_LIVE_UPDATES_ENABLED: "true"
      NAMED_URL_FORMATS:
        execution_environments: <name>
        organizations: <name>
        teams: <name>++<organization.name>
        credential_types: <name>+<kind>
        credentials: <name>++<credential_type.name>+<credential_type.kind>++<organization.name>
        notification_templates: <name>++<organization.name>
        job_templates: <name>++<organization.name>
        projects: <name>++<organization.name>
        inventories: <name>++<organization.name>
        hosts: <name>++<inventory.name>++<organization.name>
        groups: <name>++<inventory.name>++<organization.name>
        inventory_sources: <name>++<inventory.name>++<organization.name>
        instance_groups: <name>
        workflow_job_templates: <name>++<organization.name>
        workflow_job_template_nodes: <identifier>++<workflow_job_template.name>++<organization.name>
        labels: <name>++<organization.name>
        applications: <name>++<organization.name>
        users: <username>
        instances: <hostname>
      NAMED_URL_GRAPH_NODES:
        execution_environments:
          fields:
            - name
          adj_list: []
        organizations:
          fields:
            - name
          adj_list: []
        teams:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        credential_types:
          fields:
            - name
            - kind
          adj_list: []
        credentials:
          fields:
            - name
          adj_list:
            - - credential_type
              - credential_types
            - - organization
              - organizations
        notification_templates:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        job_templates:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        projects:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        inventories:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        hosts:
          fields:
            - name
          adj_list:
            - - inventory
              - inventories
        groups:
          fields:
            - name
          adj_list:
            - - inventory
              - inventories
        inventory_sources:
          fields:
            - name
          adj_list:
            - - inventory
              - inventories
        instance_groups:
          fields:
            - name
          adj_list: []
        workflow_job_templates:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        workflow_job_template_nodes:
          fields:
            - identifier
          adj_list:
            - - workflow_job_template
              - workflow_job_templates
        labels:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        applications:
          fields:
            - name
          adj_list:
            - - organization
              - organizations
        users:
          fields:
            - username
          adj_list: []
        instances:
          fields:
            - hostname
          adj_list: []
...
